#!/usr/bin/env bash
set -x

source /common.sh
install_chroot_fail_on_error_trap

# Unpack SimplyPrint files
unpack /filesystem /

sudo chmod 757 /home/pi

sudo -u pi /home/pi/oprint/bin/pip install https://github.com/SimplyPrint/OctoPrint-SimplyPrint/archive/master.zip

# Cleanup
apt-get clean
