#!/usr/bin/env bash
set -x

source /common.sh
install_chroot_fail_on_error_trap

# Unpack SimplyPrint files
unpack /filesystem /
chmod 755 /home/root/bin/simplyprint_start.sh

# Install required python packages
wget https://bootstrap.pypa.io/get-pip.py -O - | python3
pip3 install --ignore-installed pyyaml requests python-crontab dbus-python

# Cleanup
apt-get clean

sudo systemctl enable simplypi.service
